(in-package #:ddr-tests)

(defparameter *map-color-kb*
  '(
    (color red)
    (color blue)
    (color green)
    (color yellow)
    (-> (all-different ?c1 ?c2 ?c3 ?c4)
        (all-different ?c1 ?c2 ?c3)
        (all-different ?c1 ?c2 ?c4)
        (all-different ?c1 ?c3 ?c4)
        (all-different ?c2 ?c3 ?c4))
    (-> (all-different ?c1 ?c2 ?c3)
        (different ?c1 ?c2)
        (different ?c1 ?c3)
        (different ?c2 ?c3))
    (-> (different ?x ?y)
        (different ?y ?x))

    (all-different red blue green yellow)

    (<- (colors-for map1 ?a ?b ?c ?d)
        (color ?a)
        (color ?b) 
        (color ?c)
        (color ?d)
        (different ?a ?b)
        (different ?a ?c)
        (different ?b ?c)
        (different ?a ?d)
        (different ?b ?d)
        (different ?c ?d))

    (<- (colors-for map2 ?a ?b ?c ?d ?e)
        (color ?a)
        (color ?b)
        (color ?c)
        (color ?d)
        (color ?e)
        (different ?a ?b)
        (different ?a ?c)
        (different ?b ?c)
        (different ?a ?d)
        (different ?c ?d)
        (different ?a ?e)
        (different ?b ?e)
        (different ?c ?e)
        (different ?d ?e))

    (<- (colors-for map3 ?a ?b ?c ?d ?e ?f)
        (color ?a)
        (color ?b)
        (color ?c)
        (color ?d)
        (color ?e)
        (color ?f)
        (different ?a ?b)
        (different ?a ?c)
        (different ?b ?c)
        (different ?a ?d)
        (different ?b ?d)
        (different ?c ?d)
        (different ?a ?e)
        (different ?b ?e)
        (different ?d ?e)
        (different ?a ?f)
        (different ?d ?f)
        (different ?e ?f))
    ))